analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1792115
  brandStrength: 0.2562724
  lightness: 0.5698925
  brandColors:
    - '#393839'
    - '#9AACB3'
    - '#C7E1E9'
    - '#FFFFFF'
    - '#AD6D51'
  rhythmicContrast: 0.4964158
typography_spectrum: 0.6756272
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6290323
favicon: null
name: Auteur II Hizq
